version: '3'

services:

  php:
    build:
      context: .
      dockerfile: ./docker-compose/php_config
    container_name: ${APP}_php
    restart: always
    volumes:
      - ../app/:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP}_nginx
    restart: unless-stopped
    ports:
     - "80:80"
    volumes:
      - ../app/:/var/www/html
      - ./docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: postgres
    restart: always
    container_name: ${APP}_db
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: fifteen

